### ISSUE TITLE
Problem generating `program_calls.txt` when RUN_LOCAL = True

### ISSUE THREAD

**Issue by ctbaum** [zeroknowledgediscovery/Cynet#2]
I'm closely following the `cynet_crime_example.pdf` and I can generate the `program_calls.txt` if RUN_LOCAL : True in the `config.yaml` but not otherwise. Following is the stacktrace after running `script5.py`
```python [Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.
XgenESeSS Command 1 has started
...
XgenESeSS Command 13 has started
Traceback (most recent call last):
  File "/Users/ctl/Job/Python/Granger/Examples/ChicagoCrime/payload/script5.py", line 20, in <module>
    XG.run(workers=10)
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/site-packages/cynet/cynet.py", line 2497, in run
    Parallel(n_jobs = workers, verbose = 1, backend = 'threading')\
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/site-packages/cynet/cynet.py", line 2467, in run_oneXG
    subprocess.check_output(args, shell=False)
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/local/Caskroom/miniconda/base/envs/ox/lib/python3.10/site-packages/cynet/bin/XgenESeSS'```

**Comment by ctbaum** [comment]
I think it has to do with OS X; reran on Ubuntu, and all good.

**Comment by ishanuc** [comment]
Yes the underlying binaries are compiled for a linux system. Will not run
on mac.
